# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ff3dd31ce95502a01616b523f62474dfbfbfb6a41870765c7159ef4f3153e304c5055d4fef46bf75ccbdcadb74f4bf604896e9dd2fad1fd0347009162064dca

test:
  secret_key_base: 5c288e82b395a43095053cb547854e77f2084e48a733c8da87bc7081bc6aa15b05268b24aaac840cdcf901ff70b897708a209f49db3a712cc41c1ceddbfe5065

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
